#!/bin/bash
set -e
source script/functions.sh

pushd ..

clone_repo "rspec"
clone_repo "rspec-core"
clone_repo "rspec-expectations"
clone_repo "rspec-mocks"

if is_mri; then
  clone_repo "rspec-rails"
fi

if rspec_support_compatible; then
  clone_repo "rspec-support"
fi

popd
