#!/bin/bash
set -e -x
source script/functions.sh

if is_mri; then
  pushd ..

  clone_repo "rspec"
  clone_repo "rspec-core"
  clone_repo "rspec-expectations"
  clone_repo "rspec-mocks"

  if [ "$MAINTENANCE_BRANCH" != "2-99-maintenance" ]; then
    clone_repo "rspec-support"
  fi

  popd
else
  echo "Not cloning all repos since we are not on MRI and they are only needed for the MRI build"
fi
