#!/bin/bash
set -e -x
source script/functions.sh

run_specs_and_record_done
run_cukes

if is_mri; then
  run_specs_one_by_one
  run_spec_suite_for "rspec-core"
  run_spec_suite_for "rspec-expectations"
  run_spec_suite_for "rspec-mocks"

  if [ "$MAINTENANCE_BRANCH" != "2-99-maintenance" ] && [ "$MAINTENANCE_BRANCH" != "2-14-maintenance" ]; then
    run_spec_suite_for "rspec-support"
  fi
else
  echo "Skipping the rest of the build on non-MRI rubies"
fi
